name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'containers/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # if: (github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        container:
          - dapr-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to AWS ECR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ecr.caseyduplantis.com
      #     username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.actor }}/${{ matrix.container }}
            ghcr.io/${{ github.actor }}/${{ matrix.container }}
            docker.io/${{ github.actor }}/${{ matrix.container }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            
      # New step to convert the output to comma-separated list
      - name: Convert Docker tags to CSV
        id: csv_tags
        run: |
          tags_csv=$(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ',' | sed 's/,$//')
          echo "tags_csv=$tags_csv"
          echo "DOCKER_TAGS=$tags_csv" >> $GITHUB_ENV

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: containers/${{ matrix.container }}
          imageName: ghcr.io/${{ github.actor }}/${{ matrix.container }}
          cacheFrom: ghcr.io/${{ github.actor }}/${{ matrix.container }}
          imageTag: ${{ steps.csv_tags.outputs.tags_csv }}            
          platform: linux/amd64
          push: always
          
