name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'containers/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - dapr-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to AWS ECR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ecr.caseyduplantis.com
      #     username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Extract version from git tags
        id: version
        run: |
          version=$(git tag --list "${{ matrix.container }}_*" --sort=-v:refname | head -n 1 | sed "s/${{ matrix.container }}_//")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.container }}
          imageTag: latest,${{ env.VERSION }},v${{ env.VERSION }}
          platform: linux/amd64
          subFolder: containers/${{ matrix.container }}
          push: always
