name: Build and push images

on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'containers/**/devcontainer.json'

env:
    REGISTRY: ghcr.io        
    
jobs:
  build-and-push:
    name: Build and push images
    # if: ${{ github.event.base_ref == 'refs/heads/main' }}
    runs-on: devcontainer-image-builder-ubuntu
    strategy:
        fail-fast: false
        matrix:
          container: [dapr-dev]

    permissions:
        contents: read
        packages: write    
        
    env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.actor }}/${{ matrix.container }}        
        SRC_FOLDER: ./containers/${{ matrix.container }}
        
    steps:
        - name: Free more space
          id: free_space 
          run: |
            set -e
            # Ensure enough space is available for build
            sudo apt-get autoremove -y
            sudo apt-get clean -y
            sudo rm -rf /usr/share/dotnet
    
        - name: Checkout
          id: checkout
          uses: actions/checkout@v3
    
        - name: Get tag name
          id: get_tag_name  
          run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"    
        
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ github.token }}
        
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
              # list of Docker images to use as base name for tags
              images: |
                ${{ env.IMAGE_NAME }}
                ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
              # generate Docker tags based on the following events/attributes
              tags: |
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=semver,pattern={{major}}
                type=sha            

        - name: Pre-build dev container image
          uses: devcontainers/ci@v0.3
          with:
            subFolder: ${{ env.SRC_FOLDER }}
            imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            imageTag:  ${{ steps.meta.outputs.tags }}            
            push: always
        
        - name: Login to DockerHub
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        
